# Generated by Django 3.2.9 on 2021-12-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
