# Generated by Django 3.2.9 on 2022-01-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0002_auto_20211216_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=40)),
                ('comision', models.IntegerField()),
            ],
        ),
    ]
